package com.example.Student_Library_Management_System.Services;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    StudentRepository studentRepository;
    public String createStudent(Student student){
        // student form the postman is already the basic attributes set like name,mail,age,country.
        // card should be autogenerated when createStudent function is called.
        Card card=new Card();
        card.setCardStatus(CardStatus.ACTIVATED);// this attribute has been set before start in db.
        card.setStudentVariableName(student);// foreign Key column attributes values and this attribute has been set before start in db.

        // let's go to the student
        student.setCard(card);

        // If there was a  unidirectional mapping: we had to save both of them
        // but we are super advance and using bidirectional : child will automatically be saved.
        studentRepository.save(student);
        // By cascading effect , child will automatically be saved.

        return "student and card added";
    }
}
